codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "bench/**"
  - "docs/**"
  - "examples/**"
  - "notebooks/**"
  - "site/**"
  - "tests/**"
  - "src/modssc/inductive/**"
  - "src/modssc/supervised/backends/torch/**"
  - "src/modssc/transductive/methods/gnn/**"
  - "src/modssc/transductive/methods/advanced/**"
  - "src/modssc/transductive/methods/classic/label_propagation.py"
  - "src/modssc/transductive/methods/classic/label_spreading.py"
  - "src/modssc/transductive/methods/pde/poisson_learning.py"
